repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout
        files: '^(?!examples/demo\.ipynb).*'

  - repo: local
    hooks:
      - id: nbstripout-keep-output
        name: nbstripout (keep output)
        entry: uv run nbstripout --keep-output
        language: system
        files: examples/demo\.ipynb
      - id: ty
        name: ty
        entry: uv tool run ty check src
        language: system
        pass_filenames: false
